---
# - name: check if lazydocker is installed
#   shell: command -v lazydocker
#   register: lazydocker_exists
#   ignore_errors: true
#
# - name: check if go is installed
#   shell: command -v go
#   register: go_exists
#   ignore_errors: true
#

- name: install golang
  tags: go
  become: true
  apt:
    name: golang-go
    state: present

- name: "install lazydocker"
  tags: go
  shell: go install github.com/jesseduffield/lazydocker@latest
