---
- name: check if lazydocker is installed
  shell: command -v lazydocker
  register: lazydocker_exists
  ignore_errors: true

- name: check if go is installed
  shell: command -v go
  register: go_exists
  ignore_errors: true

- name: "install lazydocker"
  shell: go install github.com/jesseduffield/lazydocker@latest
  when: lazydocker_exists is failed and go_exists is failed
