---
- hosts: 192.168.0.180
  # - hosts: localhost
  connection: local
  vars_files:
    - ./vars/localhost.yml

  roles:
    - apt
    - rust
    - nvim-build
    - helm
    - nvim-config
    - tmux
    - zsh
    - vault
    - cargo
    - lazydocker
    - kitty
