---
- name: check if config exists
  stat:
    path: "{{ansible_user_dir}}/.config/nvim/init.lua"
  register: config

- name: Clone Config
  ansible.builtin.git:
    clone: yes
    dest: "{{ansible_user_dir}}/.config/nvim"
    repo: "https://github.com/adgai19/nvim-config.git"
    update: yes
    accept_hostkey: true
    # accept_newhostkey: true
    single_branch: yes
  when: not config.stat.exists

- name: sync packages
  shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
