---
- name: get zsh
  tags: zsh
  package:
    name: zsh
    state: latest

- name: Set default
  tags: zsh
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: true

- name: check for Existing install
  tags: zsh
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: install

- name: Download oh-my-zsh
  tags: zsh
  get_url:
    dest: /tmp/zsh-install.sh
    mode: 0755
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  when: not install.stat.exists

- name: Execute zsh-install.sh
  shell: /tmp/zsh-install.sh
  tags: zsh
  when: not install.stat.exists

- name: Remove zsh-install.sh
  tags: zsh
  file:
    path: /tmp/zsh-install.sh
    state: absent

- name: Clone zsh-autosuggestions
  tags: zsh
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    repo: https://github.com/zsh-users/zsh-autosuggestions
    single_branch: yes
    update: yes
    version: master

- name: Clone zsh-completions
  tags: zsh
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    repo: https://github.com/zsh-users/zsh-completions
    single_branch: yes
    update: yes
    version: master

- name: Clone zsh-syntax-highlighting
  tags: zsh
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    single_branch: yes
    update: yes
    version: master

- name: Clone zsh-z
  tags: zsh
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-z"
    repo: https://github.com/agkozak/zsh-z
    single_branch: yes
    update: yes

- name: copy zshrc to home folder
  tags: zsh
  copy:
    dest: "{{ansible_user_dir}}/.zshrc"
    src: zshrc
