---
- name: check if kitty is installed
  tags: kitty
  shell: command -v kitty
  register: kitty_exists
  ignore_errors: true

- name: Download Installer
  when: kitty_exists is failed
  get_url:
    url: https://sw.kovidgoyal.net/kitty/installer.sh
    dest: /tmp/kitty_installer.sh
    mode: "0755"
    force: "yes"
  tags:
    - kitty

- name: install rust/cargo
  when: kitty_exists is failed
  shell: /tmp/kitty_installer.sh
  tags:
    - kitty

- name: remove kitty installer
  when: kitty_exists is failed
  shell: /tmp/sh.rustup.rs
  tags:
    - kitty

- name: copy kitty config
  tags:
    - kitty
  copy:
    src: kitty.conf
    dest: "{{ansible_user_dir}}/.config/kitty/kitty.conf"

- name: copy kitty theme
  tags:
    - kitty
  copy:
    src: kitty_tokyonight_night.conf
    dest: "{{ansible_user_dir}}/.config/kitty/kitty_tokyonight_night.conf"
