---
- name: Dependancies
  tags: nvim
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present

- name: check if nvim build dir is present
  tags: nvim
  stat:
    path: "{{ ansible_user_dir }}/github/neovim"
  register: build

- name: get latest tags
  tags: nvim
  command:
    chdir: "{{ ansible_user_dir }}/github/neovim"
    cmd: git fetch --tags -f
  when: build.stat.exists

- name: Clone neovim
  tags: nvim
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/github/neovim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    single_branch: yes
    update: yes
    # version: "{{ neovim_version | default('master') }}"
  register: clone

- name: Build Neovim
  tags: nvim
  community.general.make:
    chdir: "{{ ansible_user_dir }}/github/neovim"
    jobs: 8
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: clone.changed

- name: Install Neovim
  tags: nvim
  make:
    target: install
    chdir: "{{ ansible_user_dir }}/github/neovim"
  become: true
  when: clone.changed
